8 1 True
Attained total reward at 1th episode: -15.61, total_step : 1662
total time is  {3.2202365398406982}
Traceback (most recent call last):
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/algorithms/dyna-q.py", line 210, in <module>
    average_rewards = dyna_q(args) # reward
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/algorithms/dyna-q.py", line 155, in dyna_q
    wandb.log("total rewards", total_reward)
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1820, in log
    self._log(data=data, step=step, commit=commit)
  File "/workspace/2023_Fall_GL_RL/RL/Lightning-Core-RL/.venv/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1590, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary